apiVersion: batch/v1
kind: Job
metadata:
  name: run-migrations
  namespace: bahn-alarm
spec:
  # one hour
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      imagePullSecrets:
        - name: zatong-registry-creds
      containers:
      - name: migrate
        image: registry.zat.ong/bahn-alarm-backend:latest
        imagePullPolicy: Always
        env:
          - name: CONFIGOR_DB_HOST
            value: postgres.bahn-alarm.svc.cluster.local
          - name: CONFIGOR_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: postgres-bahn-alarm-user
        envFrom:
          - secretRef:
              name: bahn-alarm-backend-settings
        command:
          - bahn-alarm
          - migrate
          - up
      restartPolicy: Never
