/**
 * Bahn Alarm
 * An app for live tracking of train delays from the DB  - In case of a request validation failure a `400` status code is returned regardless of what\'s documented - All endpoints that document a `401` response require authentication   - If the JWT is expired or invalid a `401` status code is returned   - If the `jwt` cookie is not present a `400` status code is returned
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleConnection } from './simpleConnection';

export interface DelayChangeAlarm {
  type: DelayChangeAlarm.TypeEnum;
  newDelayMinutes: number;
  connection: SimpleConnection;
}
export namespace DelayChangeAlarm {
  export type TypeEnum = 'delay-change-alarm';
  export const TypeEnum = {
    DelayChangeAlarm: 'delay-change-alarm' as TypeEnum,
  };
}
