// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: queries.sql

package squeries

import (
	"context"
)

const getUserByName = `-- name: GetUserByName :one
select id, name, passwordhash, createdat, isadmin, notificationthresholdminutes from users where name = $1 fetch first 1 row only
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Passwordhash,
		&i.Createdat,
		&i.Isadmin,
		&i.Notificationthresholdminutes,
	)
	return i, err
}
