bind: ":8090"
debug: true
db:
  dsn: user=postgres password=pass dbname=bahn_alarm sslmode=disable
bahn:
  api-key: J5RsB5Ramw2cb9gu8XmAWg3gWBiiNutP
  base-url: https://api.prd.mobimeo.com
jwt:
  cookie: jwt
  expiration-days: 30
  secret: 6da28186bd7716bcabbd40dcdf69a177bde5ff3b3669bfab1b75c369084a08d7
request-timeout-seconds: 120