bind: ":8090"
debug: false
log-level: 0
jwt:
  cookie: jwt
  expiration-days: 30
bahn:
  api-key: J5RsB5Ramw2cb9gu8XmAWg3gWBiiNutP
  base-url: https://api.prd.mobimeo.com
requests:
  timeout-seconds: 120
db:
  user: postgres
  db-name: bahn_alarm
push-notifications:
  ttl: 30