services:
  db:
    image: postgres:15.1-bullseye
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: bahn_alarm
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
