-- +goose Up
-- +goose StatementBegin
create table bahnApiSearchResponses (
    id bigint generated by default as identity primary key,
    data jsonb
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table bahnApiSearchResponses;
-- +goose StatementEnd
