apiVersion: apps/v1
kind: Deployment
metadata:
  name: bahn-alarm-frontend
  namespace: bahn-alarm
spec:
  selector:
    matchLabels:
      app: bahn-alarm-frontend
  template:
    metadata:
      labels:
        app: bahn-alarm-frontend
    spec:
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
        - name: zatong-registry-creds
      containers:
        - name: nginx
          image: registry.zat.ong/bahn-alarm-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 100M
