apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: bahn-alarm
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube-node01
      containers:
        - name: postgres
          image: postgres:15.3-alpine3.18
          ports:
            - containerPort: 5432
          resources:
            limits:
              memory: 500M
              cpu: 300m
          env:
            - name: POSTGRES_DB
              value: bahn_alarm
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-bahn-alarm-user
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bahn-alarm-postgres
  serviceName: postgres-headless
